name: Run News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'   # هر ساعت اجرا شود

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai requests urllib3

      - name: Run news scraper
        run: python news.py

      - name: Generate AI posts
        env:
          GAPGPT_API_KEY: ${{ secrets.GAPGPT_API_KEY }}
        run: python processor.py

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add news.txt rubika_posts.txt || echo "Nothing to add"
          git commit -m "auto update via GitHub Actions" || echo "Nothing to commit"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
