name: News Bot

on:
  workflow_dispatch: # اجرای دستی
  schedule:
    - cron: '0 */6 * * *' # اجرای خودکار هر 6 ساعت

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} # استفاده از توکن برای دسترسی به ریپو

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser openai

      - name: Run script and generate news.txt
        run: python news.py

      - name: Generate AI posts (Rubika)
        env:
          GAPGPT_API_KEY: ${{ secrets.GAPGPT_API_KEY }}
        run: python processor.py

      - name: Commit files to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add news.txt rubika_posts.txt
          git commit -m "Update news and AI posts" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
